### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
  description: 用于 Windows Desktops 的  Microsoft Application Virtualization Hosting 4.6 遵循固定生命周期策略。
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "806280"
name: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
summary: "用于 Windows Desktops 的  Microsoft Application Virtualization Hosting 4.6 遵循[固定](/lifecycle/policies/fixed)生命周期策略。 \n\n这适用于以下版本：Windows Desktops\n\n"
products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>链接 \n* [产品和迁移信息](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service Pack 策略](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> 由于 App-V 4.6 客户端使用 App-V 4.5 服务器，因此在与受支持的 App-V 4.6 客户端一起使用时，App-V 4.5 服务器将继续根据 App-V 4.6 的生命周期日期得到支持。\n\n## <a name=\"editions\"></a>版本 \n* 适用于 Windows 桌面"
