### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops 遵循固定生命周期策略。
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 8a32729ae5fbf7f57a14b6a6ec048c7a1f412a52
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935439"
name: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 4.6 for Windows Desktops 遵循[固定](/lifecycle/policies/fixed)生命周期策略。


  这适用于以下版本：Windows 桌面版

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>链接 \n* [产品和迁移信息](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service Pack 策略](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> 由于 App-V 4.6 客户端使用 App-V 4.5 服务器，因此在与受支持的 App-V 4.6 客户端一起使用时，App-V 4.5 服务器将继续根据 App-V 4.6 的生命周期日期得到支持。\n\n## <a name=\"editions\"></a>版本 \n* Windows 桌面版"
