### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security 遵循固定生命周期策略。
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908640"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security 遵循 [固定](/lifecycle/policies/fixed) 生命周期策略。


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>链接 \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront 客户端安全已停止。 支持将在2015年7月14日结束。 在对产品版本的支持结束后，反恶意软件和反间谍软件定义更新将不再可用。 请将 System Center Endpoint Protection 评估为替代。"
