### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.0 for Windows Desktops
  description: 适用于 Windows Desktops 的 Microsoft Application Virtualization Hosting 5.0 遵循固定生命周期策略。
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.0 for Windows Desktops
summary: |+
  Microsoft Application Virtualization Hosting 5.0 for Windows Desktops 遵循[固定](/lifecycle/policies/fixed)生命周期策略。

  这适用于以下版本：Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Service Pack 3
    startDate: 12/08/2014
    endDate: 04/14/2026
  - version: Service Pack 2
    startDate: 11/08/2013
    endDate: 01/12/2016
  - version: Service Pack 1
    startDate: 04/10/2013
    endDate: 01/13/2015
  - version: Original Release
    startDate: 11/01/2012
    endDate: 07/08/2014
content: |

  ## <a name="links"></a>链接 
  * [产品信息](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Service Pack 策略](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>版本 
  * 适用于 Windows 桌面