### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 遵循固定生命周期策略。
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "849541"
name: Microsoft System Center Configuration Manager 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 遵循[固定](/lifecycle/policies/fixed)生命周期策略。



  > [!IMPORTANT]

  > 对此产品的支持已结束。 请参阅下面的迁移指南。
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>链接 \n* [迁移指南](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [其他迁移指南](/mem/configmgr/core/migration/planning-for-migration)"
