### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: Microsoft System Center Configuration Manager 2007 遵循固定生命周期策略。
  ms.date: 07/28/2020
  ms.openlocfilehash: 796670fd93547cc79f69c544085070efb0116650
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "806161"
name: Microsoft System Center Configuration Manager 2007
summary: >
  Microsoft System Center Configuration Manager 2007 遵循[固定](/lifecycle/policies/fixed)生命周期策略。



  > [!IMPORTANT]

  > 对此产品的支持已结束。 请参阅下面的迁移指南。
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Service Pack 2
  startDate: 10/22/2009
  endDate: 07/09/2019
- version: Service Pack 1
  startDate: 05/21/2008
  endDate: 01/11/2011
- version: Original Release
  startDate: 11/29/2007
  endDate: 07/14/2009
content: "\n## <a name=\"links\"></a>链接 \n* [迁移指南](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [产品信息](/mem/configmgr/core/understand/introduction)\n* [Service pack 策略](/lifecycle/policies/fixed#service-packs)"
