### YamlMime:Lifecycle
metadata:
  title: PixelSense 应用程序套件1。0
  description: PixelSense 应用程序套件1.0 遵循固定生命周期策略。
  ms.date: 07/28/2020
  ms.openlocfilehash: 5359b0dd917124f3b47cb74f30a3ff92657c2155
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "806117"
name: PixelSense 应用程序套件1。0
summary: >+
  PixelSense 应用程序套件1.0 遵循[固定](/lifecycle/policies/fixed)生命周期策略。


products:
- windows
policyType: fixed
supportDates:
  start: 01/01/2009
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 1
  startDate: 08/09/2009
  endDate: 01/08/2019
- version: Original Release
  startDate: 01/01/2009
  endDate: 01/14/2014
content: ''
